### ISSUE TITLE
Check RUN instructions

### ISSUE THREAD

**Issue by jonesse3** [JDACS4C-IMPROVE/DeepTTC#11]
https://github.com/JDACS4C-IMPROVE/DeepTTC/blob/3e644aaafa6ea9c2b157a2f31ffc39fa168a10c5/README.md?plain=1#L54

Since the DeepTTC.build is not in this repo, I tried using the DeepTTC.default as the config file. However, I got this error when running it (after copying file to `candle_data_dir`):
```
Traceback (most recent call last):
  File "/lambda_stor/homes/ac.sejones/test/DeepTTC/DeepTTC_candle.py", line 282, in <module>
    main()
  File "/lambda_stor/homes/ac.sejones/test/DeepTTC/DeepTTC_candle.py", line 269, in main
    gParameters = initialize_parameters()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/lambda_stor/homes/ac.sejones/test/DeepTTC/DeepTTC_candle.py", line 232, in initialize_parameters
    gParameters[path] = os.path.join(candle_data_dir, gParameters[path])
                                                      ~~~~~~~~~~~^^^^^^
KeyError: 'train_data_rna'
```

**Comment by AlexandrNP** [comment]
The run file is either deepttc_baseline_pytorch.py or individual preprocess/train/infer files. DeepTTC.build for Singularity can be found in Singularity repository.
