### ISSUE TITLE
Duplicate options error:  'model_name' in section 'Global_Params' already exists

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/DeepTTC#3]
I am getting a duplicate option error.

`train.sh 1 ./data/ --epochs 1`

....
```
+ python /usr/local/DeepTTC//deepttc_baseline_pytorch.py --epochs 1
Importing candle utils for pytorch
model name:  deepttc
Traceback (most recent call last):
  File "/usr/local/DeepTTC//deepttc_baseline_pytorch.py", line 278, in <module>
    main()
  File "/usr/local/DeepTTC//deepttc_baseline_pytorch.py", line 265, in main
    gParameters = initialize_parameters()
  File "/usr/local/DeepTTC//deepttc_baseline_pytorch.py", line 220, in initialize_parameters
    gParameters = candle.finalize_parameters(common)
  File "/opt/conda/lib/python3.10/site-packages/candle/parsing_utils.py", line 790, in finalize_parameters
    fileParameters = bmk.read_config_file(
  File "/opt/conda/lib/python3.10/site-packages/candle/benchmark_def.py", line 181, in read_config_file
    config.read(file)
  File "/opt/conda/lib/python3.10/configparser.py", line 699, in read
    self._read(fp, filename)
  File "/opt/conda/lib/python3.10/configparser.py", line 1098, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '/usr/local/DeepTTC/DeepTTC.default' [line 19]: option 'model_name' in section 'Global_Params' already exists
+ python /usr/local/DeepTTC//deepttc_baseline_pytorch.py --epochs 1
Importing candle utils for pytorch
model name:  deepttc
Traceback (most recent call last):
  File "/usr/local/DeepTTC//deepttc_baseline_pytorch.py", line 278, in <module>
    main()
  File "/usr/local/DeepTTC//deepttc_baseline_pytorch.py", line 265, in main
    gParameters = initialize_parameters()
  File "/usr/local/DeepTTC//deepttc_baseline_pytorch.py", line 220, in initialize_parameters
    gParameters = candle.finalize_parameters(common)
  File "/opt/conda/lib/python3.10/site-packages/candle/parsing_utils.py", line 790, in finalize_parameters
    fileParameters = bmk.read_config_file(
  File "/opt/conda/lib/python3.10/site-packages/candle/benchmark_def.py", line 181, in read_config_file
    config.read(file)
  File "/opt/conda/lib/python3.10/configparser.py", line 699, in read
    self._read(fp, filename)
  File "/opt/conda/lib/python3.10/configparser.py", line 1098, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '/usr/local/DeepTTC/DeepTTC.default' [line 19]: option 'model_name' in section 'Global_Params' already exists
```

**Comment by wilke** [comment]
Test with `train.sh 1 ./data/ --epochs 1`

If the test.sh script is not in the same directory as the model script set IMPROVE_MODEL_DIR to the directory of the model script.

**Comment by AlexandrNP** [comment]
Fixed
