### ISSUE TITLE
DeepTTC: DataFrame' object has no attribute 'append'.

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/DeepTTC#7]
Command: `train.sh 4 /candle_data_dir`

Output:
```
PRAD              818
MB                546
CLL               272
ACC               137
Name: count, dtype: int64
Traceback (most recent call last):
  File "/usr/local/DeepTTC/deepttc_baseline_pytorch.py", line 279, in <module>
    main()
  File "/usr/local/DeepTTC/deepttc_baseline_pytorch.py", line 271, in main
    run(args)
  File "/usr/local/DeepTTC/deepttc_baseline_pytorch.py", line 247, in run
    train_drug, test_drug, train_rna, test_rna = loader.load_data()
  File "/usr/local/DeepTTC/deepttc_baseline_pytorch.py", line 133, in load_data
    train_drug, test_drug, train_rna, test_rna = self._process_data(self.args)
  File "/usr/local/DeepTTC/deepttc_baseline_pytorch.py", line 188, in _process_data
    train_drug, test_drug = obj.Getdata.ByCancer(random_seed=args.rng_seed)
  File "/usr/local/DeepTTC/Step1_getData.py", line 213, in ByCancer
    train_data, test_data = self._split(df=drug_cell_df, col=self.cancer_id,
  File "/usr/local/DeepTTC/Step1_getData.py", line 175, in _split
    train_data = train_data.append(sub_train)
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?
```

**Comment by AlexandrNP** [comment]
Issue occurs with pandas 2.0. Added requirement.txt file that specifies acceptable pandas version
